apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: tp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: toricruz/mysql-local:1.0
          imagePullPolicy: IfNotPresent
          # força o mysqld a bindar em todas as interfaces
          command: ["mysqld"]
          args:
            - "--bind-address=0.0.0.0"
            - "--mysqlx-bind-address=0.0.0.0"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            # (opcional, mantém o override via ConfigMap também)
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/zzz-docker.cnf
              subPath: my.cnf
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-config
          configMap:
            name: mysql-config
