spring.data.mongodb.uri=mongodb://mongo:0712@victoria-cruz-at-springboot_academico-mongo:27017/academico_db?authSource=admin
spring.data.mongodb.database=academico_db

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
